import type { ThemeConfig } from '@/types/notebook'

export const lightTheme: ThemeConfig = {
  foreground: '#333333',
  background: '#f5f5f5',
  editorBackground: '#ffffff',
  editorForeground: '#333333',
  border: '#cccccc',
  sidebarBackground: '#f3f3f3',
  sidebarHeader: '#e8e8e8',
  sidebarBorder: '#ddd',
  activityBarBackground: '#e8e8e8',
  activityBarForeground: '#555555',
  activityBarActiveBorder: '#007acc',
  statusBarBackground: '#007acc',
  statusBarForeground: '#ffffff',
  cellBackground: '#ffffff',
  cellSelectedBackground: '#e8f4fd',
  cellBorder: '#1a73e8',
  cellOutputBackground: '#fafafa',
  cellOutputBorder: '#dddddd',
  cellGutter: '#f5f5f5',
  toolbarBackground: '#f0f0f0',
  toolbarHover: '#e0e0e0',
  primaryButton: '#007acc',
  primaryButtonHover: '#005a9e',
  errorBackground: '#ffebee',
  errorBorder: '#ef9a9a',
  errorText: '#c62828',
  scrollbar: '#c1c1c1',
  inputBackground: '#ffffff',
  inputBorder: '#ccc',
  panelBackground: '#f3f3f3',
  panelBorder: '#ddd',
  listItemHover: '#e0e0e0',
  listItemSelected: '#007acc',
}

export const darkTheme: ThemeConfig = {
  foreground: '#d4d4d4',
  background: '#1e1e1e',
  editorBackground: '#1e1e1e',
  editorForeground: '#d4d4d4',
  border: '#3c3c3c',
  sidebarBackground: '#252526',
  sidebarHeader: '#2d2d2d',
  sidebarBorder: '#3c3c3c',
  activityBarBackground: '#333333',
  activityBarForeground: '#ffffff',
  activityBarActiveBorder: '#ffffff',
  statusBarBackground: '#007acc',
  statusBarForeground: '#ffffff',
  cellBackground: '#1e1e1e',
  cellSelectedBackground: '#264f78',
  cellBorder: '#0e639c',
  cellOutputBackground: '#252526',
  cellOutputBorder: '#3c3c3c',
  cellGutter: '#2d2d2d',
  toolbarBackground: '#2d2d2d',
  toolbarHover: '#3c3c3c',
  primaryButton: '#0e639c',
  primaryButtonHover: '#1177bb',
  errorBackground: '#5a1d1d',
  errorBorder: '#be1100',
  errorText: '#f48771',
  scrollbar: '#424242',
  inputBackground: '#3c3c3c',
  inputBorder: '#555',
  panelBackground: '#252526',
  panelBorder: '#3c3c3c',
  listItemHover: '#2d2d2d',
  listItemSelected: '#0e639c',
}
